import * as stylex from '@stylexjs/stylex';
import { colors, scale, surface, typography } from '@whip/ui/tokens.stylex';

export const styles = stylex.create({
  dialog: { width: 'min(840px, calc(100vw - 24px))', height: { default: 592, [scale.phone]: 'min(720px, calc(100dvh - 24px))' }, maxHeight: 'calc(100dvh - 24px)', padding: 0, gap: 0, overflow: 'hidden' },
  header: { paddingBlock: 16, paddingInline: 24, alignItems: 'center', height: 76, flexShrink: 0, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.border },
  body: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, gap: 0 },
  workspace: { display: 'flex', flexDirection: 'column', flex: 1, minHeight: 0, overflowY: { default: 'hidden', '@media (max-height: 600px)': 'auto' } },
  host: { display: 'flex', alignItems: 'center', gap: 8, fontSize: typography.size12, lineHeight: '18px', minWidth: 0, whiteSpace: 'nowrap' },
  hostName: { minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis' },
  connectionStatus: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0 },
  hostDetail: { display: { default: 'block', [scale.phone]: 'none' }, minWidth: 0, maxWidth: 260, overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis' },
  dot: { width: 5, height: 5, flexShrink: 0, borderRadius: '50%', backgroundColor: surface.secondaryText },
  connected: { backgroundColor: colors.success },
  navigation: { display: 'flex', alignItems: 'center', gap: 8, paddingBlock: 8, paddingInline: 16, minHeight: 52, flexShrink: 0, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.border },
  breadcrumbs: { display: 'flex', alignItems: 'center', flex: 1, minWidth: 0, overflowX: 'auto', whiteSpace: 'nowrap' },
  crumb: { display: 'flex', alignItems: 'center', flexShrink: 0 },
  crumbButton: { paddingInline: 8, maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis' },
  pathForm: { display: 'flex', alignItems: 'center', gap: 8, width: '100%', flexWrap: { default: 'nowrap', [scale.phone]: 'wrap' } },
  pathInput: { fontFamily: typography.mono, fontSize: typography.size12, flex: { default: '1 1 0', [scale.phone]: '1 1 100%' } },
  browser: { display: 'flex', flex: { default: '1 1 0', '@media (max-height: 600px)': '0 0 320px' }, minHeight: 0 },
  mobileLocations: { display: { default: 'none', [scale.phone]: 'flex' }, flexShrink: 0, paddingInline: 12, borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.border },
  locations: { display: { default: 'flex', [scale.phone]: 'none' }, flexDirection: 'column', width: 168, flexShrink: 0, padding: 12, paddingTop: 16, borderRightWidth: 1, borderRightStyle: 'solid', borderRightColor: colors.border, backgroundColor: surface.navigation, overflowY: 'auto' },
  locationLabel: { margin: 0, paddingInline: 10, paddingBottom: 8, fontSize: typography.size12, color: surface.secondaryText },
  recentLabel: { margin: 0, paddingInline: 10, paddingTop: 24, paddingBottom: 8, fontSize: typography.size12, color: surface.secondaryText, overflowWrap: 'anywhere' },
  location: { justifyContent: 'flex-start', paddingInline: 10, width: '100%', minWidth: 0 },
  locationFoot: { marginTop: 'auto', paddingTop: 24, paddingInline: 10, display: 'flex', alignItems: 'center', gap: 6, fontSize: typography.size12, color: surface.secondaryText },
  content: { display: 'flex', flexDirection: 'column', flex: 1, minWidth: 0, minHeight: 0, paddingBlock: 12, paddingInline: 16 },
  filters: { display: 'flex', gap: 16, alignItems: 'center', flexShrink: 0, flexWrap: { default: 'nowrap', [scale.phone]: 'wrap' }, paddingBottom: 12 },
  search: { display: 'flex', flex: { default: '1 1 0', [scale.phone]: '1 1 100%' }, minWidth: 0, alignItems: 'center', paddingInlineStart: 10, borderWidth: 1, borderStyle: 'solid', borderColor: { default: surface.quietBorder, ':focus-within': surface.secondaryText }, borderRadius: 6, color: surface.secondaryText },
  searchInput: { borderWidth: 0, backgroundColor: 'transparent', minWidth: 0 },
  listHeader: { display: 'flex', justifyContent: 'space-between', paddingInline: 12, minHeight: 28, alignItems: 'center', borderBottomWidth: 1, borderBottomStyle: 'solid', borderBottomColor: colors.border, fontSize: typography.size12, color: surface.secondaryText, flexShrink: 0 },
  listBody: { flex: 1, minHeight: 0, overflowY: 'auto', scrollbarGutter: 'stable' },
  list: { listStyle: 'none', padding: 0, margin: 0 },
  row: { display: 'flex', alignItems: 'center', borderRadius: 6, paddingInlineEnd: 8, minWidth: 0, backgroundColor: { default: 'transparent', ':hover': colors.hover } },
  selected: { backgroundColor: colors.hover },
  rowSelect: { display: 'flex', flex: 1, minWidth: 0, justifyContent: 'flex-start', gap: 10, height: { default: 40, [scale.touch]: 44 }, paddingInline: 12, fontWeight: 400, backgroundColor: 'transparent' },
  iconSlot: { display: 'flex', width: 20, flexShrink: 0 },
  checkSlot: { display: 'flex', width: 24, flexShrink: 0, justifyContent: 'center' },
  name: { flex: 1, minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', textAlign: 'start' },
  dimmed: { opacity: 0.45 },
  empty: { display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', minHeight: '100%', gap: 12, padding: 24, textAlign: 'center', color: surface.secondaryText, fontSize: typography.size13, lineHeight: '20px' },
  errorDetail: { overflowWrap: 'anywhere', maxWidth: '100%' },
  listFooter: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 8, height: { default: 48, [scale.phone]: 64 }, flexShrink: 0, overflowY: 'auto', paddingTop: 8, color: surface.secondaryText, fontSize: typography.size12 },
  footer: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: { default: 24, [scale.phone]: 12 }, flexShrink: 0, minHeight: 114, paddingBlock: 16, paddingInline: 24, borderTopWidth: 1, borderTopStyle: 'solid', borderTopColor: colors.border, flexWrap: { default: 'nowrap', [scale.phone]: 'wrap' } },
  selection: { display: 'flex', flexDirection: 'column', flex: { default: '1 1 0', [scale.phone]: '1 1 100%' }, minWidth: 0, gap: 4 },
  caption: { fontSize: typography.size12, lineHeight: '18px', color: surface.secondaryText },
  selectedPath: { fontFamily: typography.mono, fontSize: typography.size12, lineHeight: '20px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' },
  selectionStatus: { height: 36, overflowY: 'auto' },
  listStatus: { display: 'flex', gap: 12, alignItems: 'center' },
  loading: { display: 'flex', alignItems: 'center', gap: 6, fontSize: typography.size12 },
  skeletonRow: { display: 'flex', alignItems: 'center', gap: 10, height: { default: 40, [scale.touch]: 44 }, paddingInline: 12, color: colors.border },
  skeletonLine: { height: 10, width: '35%', borderRadius: 4, backgroundColor: colors.element },
  selectionError: { fontSize: typography.size12, lineHeight: '18px', color: colors.error, overflowWrap: 'anywhere', maxHeight: 54, overflowY: 'auto' },
  actions: { display: 'flex', alignItems: 'center', gap: 8, flexShrink: 0, marginInlineStart: 'auto' },
});
