/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as NewDraftIdRouteImport } from './routes/new.$draftId'
import { Route as HRuntimeIdSRootIdRouteImport } from './routes/h.$runtimeId.s.$rootId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewDraftIdRoute = NewDraftIdRouteImport.update({
  id: '/new/$draftId',
  path: '/new/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const HRuntimeIdSRootIdRoute = HRuntimeIdSRootIdRouteImport.update({
  id: '/h/$runtimeId/s/$rootId',
  path: '/h/$runtimeId/s/$rootId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/new/$draftId': typeof NewDraftIdRoute
  '/h/$runtimeId/s/$rootId': typeof HRuntimeIdSRootIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/new/$draftId': typeof NewDraftIdRoute
  '/h/$runtimeId/s/$rootId': typeof HRuntimeIdSRootIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/new/$draftId': typeof NewDraftIdRoute
  '/h/$runtimeId/s/$rootId': typeof HRuntimeIdSRootIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/new/$draftId' | '/h/$runtimeId/s/$rootId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/new/$draftId' | '/h/$runtimeId/s/$rootId'
  id:
    '__root__' | '/' | '/settings' | '/new/$draftId' | '/h/$runtimeId/s/$rootId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  NewDraftIdRoute: typeof NewDraftIdRoute
  HRuntimeIdSRootIdRoute: typeof HRuntimeIdSRootIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/$draftId': {
      id: '/new/$draftId'
      path: '/new/$draftId'
      fullPath: '/new/$draftId'
      preLoaderRoute: typeof NewDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$runtimeId/s/$rootId': {
      id: '/h/$runtimeId/s/$rootId'
      path: '/h/$runtimeId/s/$rootId'
      fullPath: '/h/$runtimeId/s/$rootId'
      preLoaderRoute: typeof HRuntimeIdSRootIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  NewDraftIdRoute: NewDraftIdRoute,
  HRuntimeIdSRootIdRoute: HRuntimeIdSRootIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
