import * as stylex from '@stylexjs/stylex';
import { colors, typography, surface, scale } from '@whip/ui/tokens.stylex';

export const layout = stylex.create({
  srOnly: {
    position: 'absolute',
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: 'hidden',
    clipPath: 'inset(50%)',
    whiteSpace: 'nowrap',
    borderWidth: 0,
  },
  requestDock: {
    maxHeight: 'min(72dvh, 760px)',
    overflowY: 'auto',
    flexShrink: 0,
  },
  shell: {
    height: '100dvh',
    display: 'flex',
    overflow: 'hidden',
    backgroundColor: colors.background,
    color: colors.foreground,
    fontFamily: typography.sans,
    fontSize: 13,
  },
  sidebar: {
    width: 320,
    position: 'relative',
    backgroundColor: surface.navigation,
    flexShrink: 0,
    borderRightWidth: 1,
    borderRightStyle: 'solid',
    borderRightColor: surface.quietBorder,
    display: { default: 'flex', [scale.phone]: 'none' },
    flexDirection: 'column',
    padding: 8,
    gap: 4,
  },
  sidebarSheet: { display: 'grid', gridTemplateRows: 'auto minmax(0, 1fr)', height: '100dvh', overflow: 'hidden' },
  sidebarMobile: {
    width: '100%',
    borderRightWidth: 0,
    display: 'flex',
    height: '100%',
  },
  brand: { fontWeight: 760, letterSpacing: '0.07em', fontSize: 15 },
  grow: { flex: 1, minWidth: 0, minHeight: 0 },
  row: { display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 },
  wrap: { flexWrap: 'wrap' },
  column: { display: 'flex', flexDirection: 'column', gap: 12, minWidth: 0 },
  main: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
    minHeight: 0,
  },
  header: {
    minHeight: 58,
    paddingInline: { default: 24, [scale.phone]: 12 },
    paddingBlock: 10,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: surface.quietBorder,
  },
  title: {
    fontSize: 14,
    fontWeight: 550,
    margin: 0,
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    textOverflow: 'ellipsis',
  },
  muted: { color: surface.secondaryText, fontSize: 12 },
  eyebrow: {
    fontSize: 11,
    letterSpacing: '0.03em',
    fontWeight: 550,
    color: surface.secondaryText,
  },
  mobileOnly: { display: { default: 'none', [scale.phone]: 'inline-flex' } },
  desktopOnly: { display: { default: 'inline-flex', [scale.phone]: 'none' } },
  page: {
    overflow: 'auto',
    flex: 1,
    padding: { default: 32, [scale.phone]: 16 },
    minHeight: 0,
  },
  pageInner: {
    maxWidth: 880,
    marginInline: 'auto',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
  },
  pageTitle: {
    fontWeight: 550,
    fontSize: 24,
    letterSpacing: '-0.035em',
    margin: 0,
  },
  empty: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    padding: 32,
    gap: 16,
    textAlign: 'center',
  },
  emptyTitle: {
    fontSize: { default: 28, [scale.phone]: 23 },
    letterSpacing: '-0.045em',
    fontWeight: 500,
    margin: 0,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 1.7,
    color: surface.secondaryText,
    maxWidth: 420,
    margin: 0,
  },
  sessionList: {
    position: 'relative',
    flex: 1,
    overflow: 'auto',
    minHeight: 0,
  },
  sessionLink: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    paddingBlock: 9,
    paddingInline: 10,
    borderRadius: 6,
    color: colors.foreground,
    textDecoration: 'none',
    backgroundColor: { default: 'transparent', ':hover': colors.hover },
    minHeight: { default: 48, [scale.touch]: 52 },
  },
  selected: { backgroundColor: colors.element },
  ellipsis: {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  separator: {
    border: 0,
    borderTopWidth: 1,
    borderTopStyle: 'solid',
    borderTopColor: surface.quietBorder,
    width: '100%',
    marginBlock: 8,
  },
  notice: {
    padding: '10px 16px',
    borderRadius: 8,
    backgroundColor: colors.panel,
    fontSize: 12,
    lineHeight: 1.6,
  },
  error: { color: colors.error },
  subtleButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    color: surface.secondaryText,
    padding: 8,
    borderRadius: 6,
    textDecoration: 'none',
    backgroundColor: { default: 'transparent', ':hover': colors.hover },
    cursor: 'pointer',
    borderWidth: 0,
    font: 'inherit',
    minHeight: { default: 32, [scale.touch]: 44 },
  },
  settingsRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 24,
    paddingBlock: 16,
    borderBottomWidth: 1,
    borderBottomStyle: 'solid',
    borderBottomColor: surface.quietBorder,
    flexWrap: 'wrap',
  },
  pre: {
    fontFamily: typography.mono,
    fontSize: 12,
    lineHeight: 1.65,
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    margin: 0,
    overflow: 'auto',
    maxHeight: 440,
  },
});
