import { test, expect } from '@playwright/test'

test('header matches the Paper actions and keeps theme selection in the footer', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/docs/getting-started')
  const header = page.getByRole('banner')
  await expect(header.getByRole('link')).toHaveCount(4)
  await expect(header.getByRole('navigation', { name: 'Community' }).getByRole('link').first()).toHaveAccessibleName('Discord')
  await expect(header.getByRole('navigation', { name: 'Community' }).getByRole('link').last()).toHaveAccessibleName('GitHub')
  await expect(header.getByRole('link', { name: 'GitHub', exact: true })).toHaveAttribute('href', 'https://github.com/context-labs/whip')
  await expect(header.getByRole('link', { name: 'Discord', exact: true })).toHaveAttribute('href', 'https://discord.gg/K2deYSXNu')
  const download = header.getByRole('link', { name: 'Download', exact: true })
  await expect(download).toHaveAttribute('href', 'https://github.com/context-labs/whip/releases')
  await expect(header.getByRole('link', { name: 'Documentation', exact: true })).toHaveCount(0)
  await expect(header.getByRole('button')).toHaveCount(0)
  await expect(page.getByRole('contentinfo').getByRole('button', { name: 'Colour theme: system' })).toBeVisible()
  expect((await header.boundingBox())!.height).toBe(86)
  expect((await download.boundingBox())!.height).toBe(34)
  await expect(header.locator('.header-divider')).toHaveCount(0)
  expect(await header.locator('.header-actions').evaluate(node => getComputedStyle(node).gap)).toBe('12px')
  for (const width of [320, 390]) {
    await page.setViewportSize({ width, height: 844 })
    await expect(download).toBeVisible()
    await expect(header.getByRole('link', { name: 'Discord', exact: true })).toBeVisible()
  }
})

test('theme menu follows system changes, persists and syncs across tabs', async ({ page, context }) => {
  await page.emulateMedia({ colorScheme: 'dark' })
  await page.goto('/docs/configuration')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.getByRole('button', { name: 'Colour theme: system' }).click()
  await page.getByRole('menuitemradio', { name: 'Light', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Colour theme: light' })).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  const other = await context.newPage()
  await other.goto('/docs')
  await other.getByRole('button', { name: 'Colour theme: light' }).click()
  await other.getByRole('menuitemradio', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('button', { name: 'Colour theme: dark' })).toBeVisible()
  await page.getByRole('button', { name: 'Colour theme: dark' }).click()
  await page.getByRole('menuitemradio', { name: 'System', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await other.close()
})

test('mobile navigation restores keyboard focus and follows docs links', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/docs/getting-started')
  const trigger = page.getByRole('button', { name: 'Documentation', exact: true })
  await trigger.click()
  await expect(page.getByRole('dialog', { name: 'Documentation' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.getByRole('dialog').getByRole('link', { name: 'Installation', exact: true }).click()
  await expect(page).toHaveURL('/docs/installation')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Installation')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('active sidebar text retains the inactive font weight in both themes', async ({ page }) => {
  await page.goto('/docs/getting-started')
  for (const theme of ['dark', 'light']) {
    await page.evaluate(value => { document.documentElement.dataset.theme = value }, theme)
    const active = page.locator('.docs-sidebar .sidebar-item[aria-current="page"]')
    const inactive = page.locator('.docs-sidebar .sidebar-item:not([aria-current])').first()
    await expect(active).toHaveCSS('font-weight', await inactive.evaluate(node => getComputedStyle(node).fontWeight))
    await expect(active).toHaveCSS('font-weight', '400')
  }
})

test('sidebar links and no-JS mobile disclosures remain real navigation', async ({ page, browser }) => {
  await page.goto('/docs/installation')
  await page.locator('.docs-sidebar').getByRole('link', { name: 'Configuration', exact: true }).click()
  await expect(page).toHaveURL('/docs/configuration')
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Configuration')
  const context = await browser.newContext({ javaScriptEnabled: false, viewport: { width: 390, height: 844 } })
  const mobile = await context.newPage()
  await mobile.goto('http://127.0.0.1:3101/docs/installation')
  await mobile.locator('.docs-mobile-navigation summary').click()
  await mobile.locator('.docs-mobile-navigation').getByRole('link', { name: 'Configuration', exact: true }).click()
  await expect(mobile).toHaveURL('http://127.0.0.1:3101/docs/configuration')
  await expect(mobile.getByRole('heading', { level: 1 })).toHaveText('Configuration')
  await context.close()
})

test('copy rejection provides visible manual-copy recovery', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('denied') } } }))
  await page.goto('/docs/configuration')
  await page.getByRole('button', { name: 'Copy code' }).first().click()
  await expect(page.getByRole('status').filter({ hasText: 'Copy failed. Select and copy the code manually.' })).toBeVisible()
  await expect(page.locator('pre code').first()).toBeVisible()
})
