// Command themegen exports the shared Go theme catalog and static StyleX themes.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/context-labs/whip/internal/theme"
)

func main() {
	check := flag.Bool("check", false, "fail if generated theme artifacts differ")
	out := flag.String("out", "packages/ui/src/generated", "output directory")
	flag.Parse()
	if err := run(*out, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(dir string, check bool) error {
	files, err := generate()
	if err != nil {
		return err
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	if !check {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	for _, name := range names {
		path := filepath.Join(dir, name)
		if check {
			got, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.Equal(got, files[name]) {
				return fmt.Errorf("theme contract drift: %s; run go run ./cmd/themegen", path)
			}
		} else if err := os.WriteFile(path, files[name], 0o644); err != nil {
			return err
		}
	}
	return nil
}

func generate() (map[string][]byte, error) {
	catalog, err := theme.BuiltinCatalog()
	if err != nil {
		return nil, err
	}
	var data, styles strings.Builder
	header := "// Code generated by go run ./cmd/themegen; DO NOT EDIT.\n"
	data.WriteString(header)
	writeRoles(&data, "ColorRole", reflect.TypeFor[theme.Colors]())
	writeRoles(&data, "SyntaxRole", reflect.TypeFor[theme.SyntaxSpec]())
	writeRoles(&data, "MarkdownRole", reflect.TypeFor[theme.MarkdownSpec]())
	data.WriteString(`
export interface TokenStyle {
  readonly color: string;
  readonly background: string;
  readonly bold: boolean;
  readonly italic: boolean;
  readonly underline: boolean;
}
export interface ThemeDefinition {
  readonly id: string;
  readonly name: string;
  readonly dark: boolean;
  readonly colors: Readonly<Record<ColorRole, string>>;
  readonly syntax: Readonly<Record<SyntaxRole, string>>;
  readonly markdown: Readonly<Record<MarkdownRole, string>>;
  readonly code: {
    readonly foreground: string;
    readonly background: string;
    readonly tokens: Readonly<Record<string, TokenStyle>>;
  };
}

export const themeCatalog: readonly ThemeDefinition[] = [
`)
	styles.WriteString(header + "import { createTheme } from '@stylexjs/stylex';\nimport { colors, syntax, markdown } from '../tokens.stylex';\n\n")
	ids := make([]string, 0, len(catalog))
	for i, t := range catalog {
		// Only the generated UI catalog uses camelCase. Host wire results retain
		// snake_case and are normalized at the small UI theme import boundary.
		b, _ := json.Marshal(t)
		var value map[string]any
		if err := json.Unmarshal(b, &value); err != nil {
			return nil, err
		}
		value["colors"] = camelKeys(value["colors"].(map[string]any))
		b, err = json.MarshalIndent(value, "  ", "  ")
		if err != nil {
			return nil, err
		}
		data.WriteString("  " + string(b) + ",\n")
		for _, group := range []string{"colors", "syntax", "markdown"} {
			literals, err := json.MarshalIndent(value[group], "", "  ")
			if err != nil {
				return nil, err
			}
			fmt.Fprintf(&styles, "const theme%d%s = createTheme(%s, %s);\n", i, group, group, literals)
		}
		ids = append(ids, t.ID)
	}
	data.WriteString("];\n\nexport const themeIds = ")
	encodedIDs, _ := json.Marshal(ids)
	data.Write(encodedIDs)
	data.WriteString(" as const;\nexport type BuiltinThemeID = (typeof themeIds)[number];\n")
	styles.WriteString("\nexport const themeStyles = {\n")
	for i, id := range ids {
		encodedID, _ := json.Marshal(id)
		fmt.Fprintf(&styles, "  %s: [theme%dcolors, theme%dsyntax, theme%dmarkdown],\n", encodedID, i, i, i)
	}
	styles.WriteString("} as const;\n")
	return map[string][]byte{"theme-catalog.ts": []byte(data.String()), "themes.stylex.ts": []byte(styles.String())}, nil
}

func writeRoles(out *strings.Builder, name string, t reflect.Type) {
	keys := make([]string, 0, t.NumField())
	for field := range t.Fields() {
		key := camelCase(strings.Split(field.Tag.Get("json"), ",")[0])
		quoted, _ := json.Marshal(key)
		keys = append(keys, string(quoted))
	}
	fmt.Fprintf(out, "export type %s = %s;\n", name, strings.Join(keys, " | "))
}

func camelKeys(in map[string]any) map[string]any {
	out := make(map[string]any, len(in))
	for k, v := range in {
		out[camelCase(k)] = v
	}
	return out
}

func camelCase(name string) string {
	parts := strings.Split(name, "_")
	for i := 1; i < len(parts); i++ {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}
