import * as stylex from '@stylexjs/stylex';
import { appearance, colors, scale, surface, typography } from './tokens.stylex';

export const styles = stylex.create({
  control: { fontFamily: typography.sans, fontSize: typography.size13, lineHeight: '1.5385', color: colors.foreground, borderRadius: scale.radiusControl, borderWidth: 1, borderStyle: 'solid', borderColor: surface.quietBorder, outline: {default: 'none', ':focus-visible': `1px solid ${surface.secondaryText}`}, outlineOffset: 2, minHeight: {default: 32, [scale.touch]: 44}, transitionProperty: 'background-color, border-color', transitionDuration: appearance.motionFast, backgroundColor: {default: colors.panel, ':hover': colors.hover}, opacity: {default: 1, ':disabled': 0.45}, cursor: {default: 'pointer', ':disabled': 'not-allowed'} },
  button: {display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: 6, paddingBlock: 5, paddingInline: 11, fontWeight: 530, whiteSpace: 'nowrap', userSelect: 'none', flexShrink: 0},
  primary: {backgroundColor: {default: colors.foreground, ':hover': `color-mix(in srgb, ${colors.foreground} 86%, ${colors.background})`}, color: colors.background, borderColor: 'transparent'},
  secondary: {backgroundColor: {default: colors.panel, ':hover': colors.hover}},
  ghost: {backgroundColor: {default: 'transparent', ':hover': colors.hover}, borderColor: 'transparent'},
  danger: {color: colors.error, backgroundColor: {default: `color-mix(in srgb, ${colors.error} 8%, ${colors.background})`, ':hover': `color-mix(in srgb, ${colors.error} 15%, ${colors.background})`}, borderColor: `color-mix(in srgb, ${colors.error} 32%, ${colors.background})`},
  small: {minHeight: {default: 28, [scale.touch]: 44}, paddingBlock: 3, paddingInline: 8, fontSize: typography.size12},
  large: {minHeight: 40, paddingInline: 16, fontSize: typography.size14},
  icon: {width: {default: 32, [scale.touch]: 44}, paddingInline: 0, paddingBlock: 0},
  input: {width: '100%', fontSize: {default: typography.size13, [scale.phone]: 'max(16px, var(--whip-size-13, 13px))'}, paddingBlock: 7, paddingInline: 10, backgroundColor: {default: colors.background, ':hover': colors.background}, cursor: 'text', borderColor: {default: surface.quietBorder, ':focus': surface.secondaryText}, outline: {default: 'none', ':focus-visible': 'none'}, color: {default: colors.foreground, '::placeholder': surface.secondaryText}, minWidth: 0},
  textarea: {resize: 'vertical', minHeight: 84, lineHeight: '1.55'},
  invalid: {borderColor: colors.error},
  field: {display: 'flex', flexDirection: 'column', gap: 6, minWidth: 0},
  fieldset: {borderWidth: 0, borderStyle: 'none', padding: 0, margin: 0},
  checkLabel: {minHeight: {default: 24, [scale.touch]: 44}},
  radio: {borderRadius: '50%'},
  label: {fontSize: typography.size13, lineHeight: '1.5385', fontWeight: 530, color: colors.foreground},
  optionDescription: {display: 'block'},
  description: {fontSize: typography.size12, lineHeight: '1.5', color: surface.secondaryText, margin: 0},
  error: {fontSize: typography.size12, lineHeight: '1.5', color: colors.error, margin: 0},
  inline: {display: 'inline-flex', alignItems: 'center', gap: 8},
  stack: {display: 'flex', flexDirection: 'column', gap: 12, minWidth: 0},
  row: {display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 8, minWidth: 0},
  grow: {flex: 1, minWidth: 0},
  checkbox: {width: 18, height: 18, minHeight: 18, padding: 0, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', borderRadius: 4, backgroundColor: colors.background},
  checked: {backgroundColor: colors.foreground, color: colors.background, borderColor: colors.foreground},
  switch: {width: 32, height: 20, minHeight: 20, borderRadius: 12, padding: 2, display: 'inline-flex', backgroundColor: colors.hover, borderColor: colors.border},
  switchOn: {backgroundColor: colors.foreground, borderColor: colors.foreground},
  switchThumb: {display: 'block', width: 14, height: 14, borderRadius: 10, backgroundColor: colors.background, transitionProperty: 'transform', transitionDuration: appearance.motionNormal},
  switchThumbOn: {transform: 'translateX(12px)'},
  popup: {backgroundColor: colors.panel, color: colors.foreground, border: `1px solid ${surface.quietBorder}`, borderRadius: 8, padding: 4, minWidth: 180, maxWidth: 'min(420px, calc(100vw - 24px))', maxHeight: 'min(var(--available-height), 360px)', overflow: 'auto', boxShadow: '0 8px 28px rgb(0 0 0 / 0.12)', fontSize: typography.size13, outline: 'none'},
  positioner: {zIndex: 100},
  item: {display: 'flex', alignItems: 'center', gap: 8, paddingBlock: {default: 7, [scale.touch]: 12}, paddingInline: 8, borderRadius: 4, cursor: 'default', outline: 'none', minHeight: 30},
  highlighted: {backgroundColor: colors.hover},
  disabled: {opacity: 0.45, cursor: 'not-allowed'},
  checkSlot: {width: 16, display: 'inline-flex', flexShrink: 0},
  chevron: {marginInlineStart: 'auto', color: surface.secondaryText},
  backdrop: {position: 'fixed', inset: 0, backgroundColor: surface.overlay, zIndex: 80},
  dialog: {position: 'fixed', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', width: 'min(520px, calc(100vw - 32px))', maxHeight: 'min(85dvh, 860px)', backgroundColor: colors.background, color: colors.foreground, border: `1px solid ${surface.quietBorder}`, borderRadius: scale.radiusDialog, padding: 24, display: 'flex', flexDirection: 'column', gap: 20, zIndex: 81, overflow: 'auto', boxShadow: '0 16px 64px rgb(0 0 0 / 0.16)'},
  sheet: {top: 0, right: 0, bottom: 0, left: 'auto', transform: 'none', width: 'min(440px, 100vw)', maxHeight: '100dvh', borderRadius: 0, padding: 20},
  dialogHeader: {display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 16},
  dialogTitle: {fontSize: typography.size17, fontWeight: 600, lineHeight: '1.4118', letterSpacing: '-0.015em', margin: 0},
  dialogDescription: {fontSize: typography.size13, lineHeight: '1.5385', color: surface.secondaryText, marginTop: 6, marginBottom: 0},
  footer: {display: 'flex', gap: 8, justifyContent: 'flex-end', flexWrap: 'wrap'},
  separator: {height: 1, minHeight: 1, border: 0, marginBlock: 8, backgroundColor: surface.quietBorder},
  tooltip: {fontSize: typography.size12, lineHeight: '1.5', borderRadius: 5, paddingBlock: 5, paddingInline: 8, maxWidth: 300, backgroundColor: colors.foreground, color: colors.background},
  tabList: {display: 'flex', gap: 4, borderBottom: `1px solid ${surface.quietBorder}`, overflowX: 'auto', paddingBottom: 4},
  tab: {backgroundColor: 'transparent', borderColor: 'transparent', color: surface.secondaryText},
  tabActive: {backgroundColor: colors.hover, color: colors.foreground},
  tabPanel: {paddingTop: 16, outline: 'none'},
  badge: {display: 'inline-flex', alignItems: 'center', gap: 5, paddingBlock: 2, paddingInline: 7, borderRadius: 5, fontSize: typography.size11, lineHeight: '1.5455', fontWeight: 500, whiteSpace: 'nowrap', backgroundColor: colors.element, color: surface.secondaryText},
  success: {color: colors.success, backgroundColor: `color-mix(in srgb, ${colors.success} 10%, ${colors.background})`},
  warning: {color: colors.warning, backgroundColor: `color-mix(in srgb, ${colors.warning} 10%, ${colors.background})`},
  errorTone: {color: colors.error, backgroundColor: `color-mix(in srgb, ${colors.error} 10%, ${colors.background})`},
  info: {color: colors.info, backgroundColor: `color-mix(in srgb, ${colors.info} 10%, ${colors.background})`},
  dot: {width: 6, height: 6, borderRadius: '50%', backgroundColor: 'currentColor', flexShrink: 0},
  empty: {display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', paddingBlock: 48, paddingInline: 24, gap: 12, minHeight: 200},
  emptyTitle: {fontSize: typography.size16, fontWeight: 550, margin: 0},
  emptyDescription: {fontSize: typography.size13, lineHeight: '1.6154', color: surface.secondaryText, maxWidth: 400, margin: 0},
  alert: {display: 'flex', gap: 10, padding: 12, borderRadius: 7, backgroundColor: colors.panel, border: `1px solid ${surface.quietBorder}`, fontSize: typography.size13, lineHeight: '1.5385'},
  progressTrack: {height: 4, overflow: 'hidden', borderRadius: 4, backgroundColor: colors.hover},
  progressFill: {height: '100%', borderRadius: 4, backgroundColor: colors.foreground, transitionProperty: 'width', transitionDuration: appearance.motionNormal},
  skeleton: {backgroundColor: colors.hover, borderRadius: 4, minHeight: 16},
  kbd: {fontFamily: typography.mono, fontSize: typography.size10, lineHeight: '1.6', paddingInline: 4, borderRadius: 3, border: `1px solid ${surface.quietBorder}`, color: surface.secondaryText, whiteSpace: 'nowrap'},
  link: {color: colors.link, textDecorationLine: 'underline', textUnderlineOffset: 3},
  panel: {backgroundColor: colors.panel, border: `1px solid ${surface.quietBorder}`, borderRadius: scale.radiusPanel, padding: 16},
  scroll: {overflow: 'auto', overscrollBehavior: 'contain', minHeight: 0, minWidth: 0},
  settingsRow: {display: 'flex', minWidth: 0, flexDirection: {default: 'row', [scale.phone]: 'column'}, flexWrap: 'wrap', alignItems: {default: 'center', [scale.phone]: 'stretch'}, justifyContent: 'space-between', gap: 16, paddingBlock: 16, borderBottom: `1px solid ${surface.quietBorder}`},
  avatar: {width: 28, height: 28, borderRadius: 6, backgroundColor: colors.element, color: surface.secondaryText, display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: typography.size11, fontWeight: 600, overflow: 'hidden'},
  visuallyHidden: {position: 'absolute', width: 1, height: 1, padding: 0, margin: -1, overflow: 'hidden', clipPath: 'inset(50%)', whiteSpace: 'nowrap', borderWidth: 0},
});
