// Code generated by go run ./cmd/modelgen; DO NOT EDIT.
export const providerEnvironmentNames = [
  "CEREBRAS_API_KEY",
  "DEEPINFRA_API_KEY",
  "DEEPINFRA_TOKEN",
  "DEEPSEEK_API_KEY",
  "FIREWORKS_API_KEY",
  "GROQ_API_KEY",
  "INFERENCE_API_KEY",
  "OPENAI_API_KEY",
  "OPENROUTER_API_KEY",
  "TOGETHER_API_KEY",
  "XAI_API_KEY",
] as const;
