import * as stylex from '@stylexjs/stylex';
import { colors, typography, scale } from '~/tokens.stylex';

const buttonBase = {
  display: 'inline-flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: scale.space2,
  minHeight: '32px',
  paddingTop: '8px',
  paddingBottom: '8px',
  paddingLeft: '16px',
  paddingRight: '16px',
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: colors.borderControl,
  borderRadius: scale.radiusMd,
  backgroundColor: colors.surfaceControl,
  color: colors.text,
  fontFamily: typography.sans,
  fontWeight: 500,
  fontSize: '12px',
  lineHeight: '16px',
  textDecoration: 'none',
  ':hover': { backgroundColor: colors.surfaceHover },
  ':focus-visible': { borderColor: colors.accent },
  ':disabled': {
    backgroundColor: colors.surfacePanel,
    borderColor: colors.border,
    color: colors.textMuted,
  },
} as const;

export const styles = stylex.create({
  button: buttonBase,
  // `:hover:not(:disabled)` is not expressible in StyleX; override the hover
  // background explicitly when the button is disabled.
  buttonDisabled: {
    ':hover': { backgroundColor: colors.surfacePanel },
  },
  // Kept for parity with the removed .button-secondary rule; used by callers
  // that compose the base button look.
  buttonSecondary: {
    backgroundColor: colors.bg,
    borderColor: colors.border,
  },
  iconButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    flexShrink: 0,
    padding: 0,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: scale.radiusMd,
    backgroundColor: colors.bg,
    color: colors.textMuted,
    ':hover': {
      backgroundColor: colors.surfaceHover,
      color: colors.text,
      borderColor: colors.borderControl,
    },
  },
  tooltip: {
    backgroundColor: colors.surfaceElement,
    color: colors.text,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderControl,
    borderRadius: scale.radiusMd,
    zIndex: 60,
    fontFamily: typography.sans,
    fontSize: '12px',
    lineHeight: '20px',
    paddingTop: '4px',
    paddingBottom: '4px',
    paddingLeft: '8px',
    paddingRight: '8px',
    maxWidth: '280px',
  },
  menuPopup: {
    backgroundColor: colors.surfaceElement,
    color: colors.text,
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.borderControl,
    borderRadius: scale.radiusMd,
    zIndex: 60,
    minWidth: '160px',
    padding: scale.space1,
    outlineStyle: 'none',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: scale.space2,
    paddingTop: '8px',
    paddingBottom: '8px',
    paddingLeft: '12px',
    paddingRight: '12px',
    borderRadius: scale.radiusSm,
    fontSize: typography.small,
    lineHeight: 'var(--leading-small, 20px)',
    cursor: 'pointer',
  },
  menuItemHighlighted: {
    backgroundColor: colors.surfaceHover,
    outlineWidth: '1px',
    outlineStyle: 'solid',
    outlineColor: colors.accent,
    outlineOffset: '-1px',
  },
  menuItemDisabled: {
    color: colors.textMuted,
    cursor: 'not-allowed',
  },
  menuCheck: {
    width: '14px',
    flexShrink: 0,
  },
  splitButton: {
    display: 'inline-flex',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: colors.border,
    borderRadius: scale.radiusMd,
  },
  splitButtonChild: {
    borderWidth: 0,
    borderRadius: '5px 0 0 5px',
  },
  splitTrigger: {
    borderRadius: '0 5px 5px 0',
    borderLeftWidth: '1px',
    borderLeftStyle: 'solid',
    borderLeftColor: colors.border,
    paddingLeft: '8px',
    paddingRight: '8px',
  },
});
