import * as stylex from '@stylexjs/stylex';
import { colors, typography, scale } from '~/tokens.stylex';

const codeBlockBase = {
  minWidth: 0,
  borderWidth: '1px',
  borderStyle: 'solid',
  borderColor: colors.border,
  borderRadius: scale.radiusMd,
  backgroundColor: colors.surfacePanel,
} as const;

export const styles = stylex.create({
  codeBlock: codeBlockBase,
  codeTabs: codeBlockBase,
  codeBlockTabbed: { borderWidth: 0 },
  codeHeader: {
    minHeight: '40px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: scale.space2,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: '12px',
    paddingRight: '8px',
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: colors.border,
    borderRadius: '5px 5px 0 0',
  },
  codeTabsHeader: { gap: '16px' },
  codePre: {
    margin: 0,
    padding: '20px',
    overflow: 'auto',
    maxWidth: '100%',
    borderRadius: '0 0 5px 5px',
    fontFamily: typography.mono,
    fontSize: '12px',
    lineHeight: '20px',
    whiteSpace: 'pre',
    tabSize: 2,
    color: colors.text,
    ':focus-visible': { outlineOffset: '-3px' },
  },
  // `code` inherits the <pre> font and colour; MDX prose styles target `code`
  // elements, so this neutralises them inside code blocks.
  codeCode: {
    fontFamily: 'inherit',
    fontSize: 'inherit',
    fontWeight: 'inherit',
    lineHeight: 'inherit',
    color: 'inherit',
    backgroundColor: 'transparent',
    borderWidth: 0,
    padding: 0,
  },
  codeTabList: {
    display: 'flex',
    minWidth: 0,
    overflowX: 'auto',
    alignSelf: 'stretch',
    marginBottom: '-1px',
  },
  codeTab: {
    backgroundColor: 'transparent',
    color: colors.textMuted,
    flexShrink: 0,
    borderWidth: 0,
    borderBottomWidth: '1px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: '12px',
    paddingRight: '12px',
    display: 'flex',
    alignItems: 'center',
    fontFamily: typography.sans,
    fontWeight: 500,
    fontSize: '11px',
    lineHeight: '27px',
    letterSpacing: 'var(--tracking-label, 0.08em)',
    textTransform: 'uppercase',
    ':hover': { color: colors.text },
    ':focus-visible': { outlineOffset: '-3px' },
  },
  codeTabActive: {
    color: colors.textSecondary,
    borderBottomColor: colors.textSecondary,
  },
  codeTabPanel: {
    ':focus-visible': { outlineOffset: '-3px', borderRadius: '0 0 5px 5px' },
  },
});
