import assert from 'node:assert/strict';
import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { buildInstallers } from './build-installers.mjs';

const template = await readFile(new URL('../install.sh', import.meta.url), 'utf8');

test('installer generation is deterministic, pinned, and latest is version-independent', () => {
  for (const tag of ['v1.0.0-alpha.10', 'v1.0.0', 'v2.1.0-rc.1+build.7']) {
    const installers = buildInstallers(template, tag);
    assert.deepEqual(buildInstallers(template, tag), installers);
    assert.deepEqual(Object.keys(installers), ['install.sh', 'latest.sh']);
    assert(installers['install.sh'].includes(`INSTALLER_MODE=pinned\nINSTALLER_VERSION=${tag}\n`));
    assert(installers['latest.sh'].includes('INSTALLER_MODE=latest\nINSTALLER_VERSION=\n'));
    assert.equal(installers['latest.sh'], buildInstallers(template, 'v1.0.0')['latest.sh']);
  }
});

test('CLI writes the pure generated bytes and check rejects changed bytes', async () => {
  const directory = await mkdtemp(path.join(tmpdir(), 'whipcode-installers-'));
  const script = fileURLToPath(new URL('./build-installers.mjs', import.meta.url));
  const tag = 'v1.0.0-alpha.10';
  try {
    execFileSync(process.execPath, [script, tag, directory]);
    for (const [name, expected] of Object.entries(buildInstallers(template, tag))) {
      assert.equal(await readFile(path.join(directory, name), 'utf8'), expected);
    }
    execFileSync(process.execPath, [script, tag, directory, '--check']);
    await writeFile(path.join(directory, 'latest.sh'), 'tampered');
    assert.throws(() => execFileSync(process.execPath, [script, tag, directory, '--check'], { stdio: 'pipe' }));
    assert.equal(await readFile(path.join(directory, 'latest.sh'), 'utf8'), 'tampered');
  } finally { await rm(directory, { recursive: true, force: true }); }
});

test('generation rejects invalid tags and missing or duplicated policy blocks', () => {
  for (const tag of ['', undefined, 'latest', '1.0.0', 'vv1.0.0', 'v0.9.0', 'v1', 'v01.0.0',
    'v1.0.0-alpha.01', 'v1.0.0\necho injected', 'v1.0.0;id', 'whipcode-v1.0.0', 'desktop-v1.0.0']) {
    assert.throws(() => buildInstallers(template, tag), /canonical v1/);
  }
  assert.throws(() => buildInstallers('', 'v1.0.0'), /exactly one/);
  assert.throws(() => buildInstallers(template + template, 'v1.0.0'), /exactly one/);
  assert.throws(() => buildInstallers(buildInstallers(template, 'v1.0.0')['install.sh'], 'v1.0.1'), /exactly one/);
});
