import { useEffect, useRef, useState, type PropsWithChildren, type ReactNode } from 'react';
import { AccessibilityInfo, ActivityIndicator, findNodeHandle, Platform, Pressable, ScrollView, StyleSheet, Switch, Text as NativeText, TextInput, View, type TextProps, type TextInputProps, type ViewProps } from 'react-native';
import { BottomSheet, RNHostView } from '@expo/ui';
import { FlashList } from '@shopify/flash-list';
import { ArrowLeft, Check, ChevronRight, Search, X } from 'lucide-react-native';
import { useTheme, useDisplay } from '../theme/theme';
export const tokens = { inset: 20, target: Platform.OS === 'android' ? 48 : 44, radius: { control: 12, message: 18, composer: 24, sheet: 28 } } as const;
export function Text({ muted, variant = 'body', style, ...props }: TextProps & { muted?: boolean; variant?: 'body' | 'caption' | 'title' | 'heading' | 'code' }) {
  const theme = useTheme(); const display = useDisplay();
  const size = variant === 'title' ? 30 : variant === 'heading' ? 20 : variant === 'caption' ? 13 : variant === 'code' ? display.codeSize! : 16;
  const strong = variant === 'title' || variant === 'heading' || ['bold', '600', '700'].includes(String(StyleSheet.flatten(style)?.fontWeight));
  return <NativeText {...props} style={[{ color: muted ? theme.colors.muted : theme.colors.foreground, fontSize: size * (variant === 'code' ? 1 : display.textScale!), lineHeight: size * (variant === 'code' ? 1.5 : display.textScale! * 1.5), fontFamily: variant === 'code' ? display.mono : strong ? display.semibold : display.regular, fontWeight: strong && !display.semibold ? '600' : 'normal', letterSpacing: variant === 'title' ? -0.8 : 0 }, style]} />;
}
export function Stack({ style, ...props }: ViewProps) { return <View {...props} style={[{ gap: 12 }, style]} />; }
export function Surface({ tone = 'panel', style, ...props }: ViewProps & { tone?: 'panel' | 'element' | 'background' }) { const theme = useTheme(); return <View {...props} style={[{ backgroundColor: theme.colors[tone], borderRadius: 16, padding: 16 }, style]} />; }
export function Divider() { const theme = useTheme(); return <View style={{ height: StyleSheet.hairlineWidth, backgroundColor: theme.colors.border }} />; }
export type ButtonProps = { label: string; onPress(): void; variant?: 'primary' | 'secondary' | 'quiet' | 'destructive'; disabled?: boolean; loading?: boolean; icon?: ReactNode; testID?: string };
export function Button({ label, onPress, variant = 'primary', disabled, loading, icon, testID }: ButtonProps) {
  const { colors } = useTheme(); const blocked = disabled || loading; const color = variant === 'primary' ? colors.onPrimary : variant === 'destructive' ? colors.error : colors.foreground;
  return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: !!blocked, busy: !!loading }} disabled={blocked} onPress={onPress}
    style={({ pressed }) => ({ minHeight: 52, borderRadius: 12, paddingHorizontal: 20, paddingVertical: 12, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 10, backgroundColor: variant === 'primary' ? colors.primary : pressed ? colors.hover : variant === 'quiet' ? 'transparent' : colors.element, borderWidth: variant === 'secondary' ? 1 : 0, borderColor: colors.border, opacity: blocked ? 0.5 : pressed ? 0.8 : 1 })}>
    {loading ? <ActivityIndicator color={color} /> : icon}<Text style={{ color, fontWeight: '600', textAlign: 'center' }}>{label}</Text>
  </Pressable>;
}
export function IconButton({ label, onPress, children, disabled, testID }: PropsWithChildren<{ label: string; onPress(): void; disabled?: boolean; testID?: string }>) {
  const { colors } = useTheme(); return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => ({ width: tokens.target, height: tokens.target, borderRadius: tokens.target / 2, alignItems: 'center', justifyContent: 'center', flexShrink: 0, borderWidth: StyleSheet.hairlineWidth, borderColor: colors.border, backgroundColor: pressed ? colors.hover : colors.element, opacity: disabled ? 0.45 : 1 })}>{children}</Pressable>;
}
export function TextField({ label, error, hint, style, ...props }: TextInputProps & { label: string; error?: string; hint?: string }) {
  const { colors, dark } = useTheme(); const display = useDisplay(); const [focused, setFocused] = useState(false);
  return <Stack style={{ gap: 8 }}><Text variant="caption" muted>{label}</Text><TextInput {...props} accessibilityLabel={props.accessibilityLabel ?? label} keyboardAppearance={dark ? 'dark' : 'light'} placeholderTextColor={colors.muted} selectionColor={colors.primary} onFocus={e => { setFocused(true); props.onFocus?.(e); }} onBlur={e => { setFocused(false); props.onBlur?.(e); }} style={[{ minHeight: 52, paddingHorizontal: 14, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: error ? colors.error : focused ? colors.borderFocus : colors.border, backgroundColor: colors.element, color: colors.foreground, fontFamily: display.regular, fontSize: 16 * display.textScale!, lineHeight: 24 * display.textScale! }, style]} />{(error || hint) && <Text variant="caption" accessibilityLiveRegion="polite" style={{ color: error ? colors.error : colors.muted }}>{error ?? hint}</Text>}</Stack>;
}
export function SearchField({ value, onChangeText, placeholder = 'Search…', autoFocus = false }: { value: string; onChangeText(value: string): void; placeholder?: string; autoFocus?: boolean }) {
  const { colors, dark } = useTheme(); const display = useDisplay();
  return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 12, paddingLeft: 16, borderRadius: 24, backgroundColor: colors.element, borderWidth: 1, borderColor: colors.border }}><Search size={20} color={colors.muted} /><TextInput value={value} onChangeText={onChangeText} accessibilityLabel={placeholder} placeholder={placeholder} autoFocus={autoFocus} autoCapitalize="none" autoCorrect={false} keyboardAppearance={dark ? 'dark' : 'light'} placeholderTextColor={colors.muted} selectionColor={colors.primary} style={{ flex: 1, minHeight: 52, color: colors.foreground, fontFamily: display.regular, fontSize: 16 * display.textScale! }} />{!!value && <IconButton label="Clear search" onPress={() => onChangeText('')}><X size={18} color={colors.muted} /></IconButton>}</View>;
}
export function ListRow({ title, detail, onPress, selected, disabled, leading, trailing, testID }: { title: string; detail?: string; onPress?(): void; selected?: boolean; disabled?: boolean; leading?: ReactNode; trailing?: ReactNode; testID?: string }) {
  const { colors } = useTheme();
  return <Pressable testID={testID} accessibilityRole={onPress ? 'button' : undefined} accessibilityState={{ selected, disabled }} disabled={disabled || !onPress} onPress={onPress} style={({ pressed }) => ({ minHeight: 68, paddingVertical: 16, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border, backgroundColor: pressed ? colors.hover : 'transparent', opacity: disabled ? 0.5 : 1 })}>
    {leading && <View style={{ width: 28, alignItems: 'center', flexShrink: 0 }}>{leading}</View>}<View style={{ flex: 1, gap: 4 }}><Text style={{ fontWeight: selected ? '600' : 'normal' }}>{title}</Text>{detail && <Text muted variant="caption">{detail}</Text>}</View><View style={{ minWidth: 22, flexShrink: 0 }}>{trailing ?? (selected ? <Check size={20} color={colors.primary} /> : onPress ? <ChevronRight size={18} color={colors.muted} /> : null)}</View>
  </Pressable>;
}
export function Section({ title, children }: PropsWithChildren<{ title?: string }>) { return <Stack style={{ gap: 4 }}>{title && <Text muted variant="caption" style={{ marginTop: 12, marginBottom: 8 }}>{title}</Text>}{children}</Stack>; }
export function StatusBadge({ label, tone = 'muted' }: { label: string; tone?: 'success' | 'warning' | 'error' | 'muted' | 'primary' }) { const { colors } = useTheme(); return <View style={{ flexDirection: 'row', gap: 6, alignItems: 'center' }}><View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: colors[tone] }} /><Text variant="caption" style={{ color: colors[tone] }}>{label}</Text></View>; }
export function ChoiceGroup<T extends string>({ label, value, options, onChange }: { label: string; value: T; options: readonly { value: T; label: string }[]; onChange(value: T): void }) { const { colors } = useTheme(); return <View accessibilityLabel={label} style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 4, padding: 4, borderRadius: 14, backgroundColor: colors.panel }}>{options.map(option => <Pressable key={option.value} accessibilityRole="radio" accessibilityState={{ checked: value === option.value }} accessibilityLabel={option.label} onPress={() => onChange(option.value)} style={{ flexGrow: 1, minHeight: tokens.target, padding: 10, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: value === option.value ? colors.element : 'transparent' }}><Text style={{ fontWeight: value === option.value ? '600' : 'normal' }}>{option.label}</Text></Pressable>)}</View>; }
export function SwitchRow({ label, value, onChange }: { label: string; value: boolean; onChange(value: boolean): void }) { const { colors } = useTheme(); return <ListRow title={label} trailing={<Switch accessibilityLabel={label} value={value} onValueChange={onChange} trackColor={{ false: colors.element, true: colors.primary }} thumbColor={value ? colors.onPrimary : colors.foreground} />} />; }
export function Screen({ children, scroll = true }: PropsWithChildren<{ scroll?: boolean }>) { const theme = useTheme(); return scroll ? <ScrollView keyboardShouldPersistTaps="handled" style={{ flex: 1, backgroundColor: theme.colors.background }} contentContainerStyle={{ padding: 20, paddingBottom: 40, gap: 24, width: '100%', maxWidth: 760, alignSelf: 'center' }}>{children}</ScrollView> : <View style={{ flex: 1, width: '100%', maxWidth: 760, alignSelf: 'center', backgroundColor: theme.colors.background }}>{children}</View>; }
export function ScreenHeader({ title, onBack, left, right }: { title?: string; onBack?(): void; left?: ReactNode; right?: ReactNode }) { const { colors } = useTheme(); return <View style={{ paddingHorizontal: 20, paddingVertical: 12, minHeight: 68, flexDirection: 'row', gap: 12, alignItems: 'center' }}>{left ?? (onBack ? <IconButton label="Back" onPress={onBack}><ArrowLeft size={22} color={colors.foreground} /></IconButton> : null)}<Text variant="heading" numberOfLines={2} style={{ flex: 1, textAlign: onBack ? 'center' : 'left', fontSize: 16 }}>{title}</Text>{right ?? (onBack ? <View style={{ width: tokens.target }} /> : null)}</View>; }
export function Notice({ children, danger = false }: PropsWithChildren<{ danger?: boolean }>) { const { colors } = useTheme(); return <View accessibilityLiveRegion="polite" style={{ padding: 14, borderRadius: 12, borderWidth: StyleSheet.hairlineWidth, borderColor: danger ? colors.error : colors.border, backgroundColor: colors.panel }}><Text style={{ color: danger ? colors.error : colors.muted, fontSize: 14 }}>{children}</Text></View>; }
export function Loading({ label = 'Loading…' }: { label?: string }) { const { colors } = useTheme(); return <Stack style={{ padding: 24, alignItems: 'center' }}><ActivityIndicator color={colors.primary} /><Text muted>{label}</Text></Stack>; }
export function EmptyState({ title, description, icon, action }: { title: string; description: string; icon?: ReactNode; action?: ButtonProps }) { return <Stack style={{ flex: 1, justifyContent: 'center', alignItems: 'center', padding: 32, gap: 16 }}>{icon}<Text variant="heading" style={{ textAlign: 'center' }}>{title}</Text><Text muted style={{ textAlign: 'center', maxWidth: 320 }}>{description}</Text>{action && <View style={{ marginTop: 8 }}><Button {...action} /></View>}</Stack>; }
export function Sheet({ title, visible, onClose, children, full = false }: PropsWithChildren<{ title: string; visible: boolean; onClose(): void; full?: boolean }>) {
  const theme = useTheme(); const heading = useRef<NativeText>(null);
  useEffect(() => { if (!visible) return; const timer = setTimeout(() => { const tag = findNodeHandle(heading.current); if (tag) AccessibilityInfo.setAccessibilityFocus(tag); }, 350); return () => clearTimeout(timer); }, [visible]);
  return <BottomSheet isPresented={visible} onDismiss={onClose} snapPoints={full ? ['full'] : ['half', 'full']} contentPadding={0} containerColor={theme.colors.panel}><RNHostView><View accessibilityViewIsModal style={{ flex: 1, backgroundColor: theme.colors.panel }}><View style={{ flexDirection: 'row', gap: 12, alignItems: 'center', padding: 20 }}><NativeText ref={heading} accessibilityRole="header" style={{ flex: 1, color: theme.colors.foreground, fontSize: 20, fontWeight: '600' }}>{title}</NativeText><IconButton label={`Close ${title}`} onPress={onClose}><X size={22} color={theme.colors.foreground} /></IconButton></View>{children}</View></RNHostView></BottomSheet>;
}
export function PickerList({ options, selected, onSelect, placeholder = 'Search…' }: { options: readonly { id: string; title: string; detail?: string; trailing?: ReactNode }[]; selected?: string; onSelect(id: string): void; placeholder?: string }) { const [query, setQuery] = useState(''); const filtered = options.filter(o => `${o.title} ${o.detail ?? ''}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())); return <View style={{ flex: 1, gap: 12, paddingHorizontal: 20 }}><SearchField value={query} onChangeText={setQuery} placeholder={placeholder} /><FlashList data={filtered} keyExtractor={o => o.id} keyboardShouldPersistTaps="handled" renderItem={({ item }) => <ListRow title={item.title} detail={item.detail} trailing={item.trailing} selected={selected === item.id} onPress={() => onSelect(item.id)} />} ListEmptyComponent={<Text muted style={{ paddingVertical: 24 }}>No matches. Try another search.</Text>} /></View>; }
