package protocol

import (
	"github.com/context-labs/whip/internal/session"
	"reflect"
)

func action[P, R any](name string, execution Execution, permission string, sensitive bool) Operation {
	return Operation{Name: name, Surface: "runtime", Execution: execution, Permission: permission, Sensitive: sensitive,
		Params: reflect.TypeFor[P](), Result: reflect.TypeFor[R]()}
}

var runtimeOperations = []Operation{
	action[CreateSessionParams, RootIDResult]("session.create", Command, "host-runtime", false),
	action[RootParams, RootIDResult]("session.delete", Command, "root-association", false),
	action[CheckpointParams, RestartNotice]("daemon.checkpoint", Command, "host-runtime", false),
	action[SubmitPayload, TextResult]("submit", Command, "root-admission", false),
	action[SubmitPayload, TextResult]("steer", Command, "root-admission", false),
	action[CancelParams, Empty]("cancel", Command, "target-turn", false),
	action[TextParams, GoalResult]("goal.set", Command, "root-admission", false),
	action[TextParams, GoalResult]("goal.run", Command, "root-admission", false),
	action[GoalContextParams, GoalResult]("goal.from-context", Command, "root-admission", false),
	action[EmptyParams, ScheduleListResult]("schedule.list", Query, "root-association", false),
	action[ScheduleCreateParams, ScheduleResult]("schedule.create", Command, "schedule-budget", false),
	action[ScheduleDeleteParams, ScheduleResult]("schedule.delete", Command, "root-association", false),
	action[ForkParams, RootIDResult]("session.fork", Command, "root-association", false),
	action[EmptyParams, PathResult]("workspace.inspect", Query, "root-association", false),
	action[PathParams, PathResult]("workspace.set", Command, "workspace-authority", false),
	action[EffortParams, EffortResult]("session.effort", Command, "root-idle", false),
	action[EmptyParams, EffortResult]("session.effort.get", Query, "root-association", false),
	action[ModelParams, ModelResult]("session.model", Command, "root-idle", false),
	action[EmptyParams, ModelResult]("session.model.get", Query, "root-association", false),
	action[ListParams, SessionListResult]("session.list", Query, "host-runtime", false),
	action[IDParams, RootIDResult]("session.open", Query, "root-association", false),
	action[TitleParams, TitleResult]("session.rename", Command, "root-association", false),
	action[EmptyParams, ModelResult]("session.reload", Command, "root-idle", false),
	action[EmptyParams, Empty]("session.autotitle", Command, "root-association", false),
	action[RunConfigureParams, Empty]("run.configure", Command, "root-idle", false),
	action[EmptyParams, Empty]("history.clear", Command, "root-idle", false),
	action[RewindParams, RewindResult]("history.rewind", Command, "root-idle", false),
	action[EmptyParams, CompactionResult]("history.compact", Command, "root-idle", false),
	action[EmptyParams, CompactionListResult]("history.compact.log", Query, "root-association", false),
	action[EmptyParams, CompactionRetryResult]("history.compact.retry", Command, "root-idle", false),
	action[CompactionParams, CompactionSettingsResult]("compaction.configure", Command, "root-idle", false),
	action[EmptyParams, UserHistoryResult]("history.user.list", Query, "root-association", false),
	action[IDParams, SessionPreviewResult]("session.preview", Query, "root-association", false),
	action[EmptyParams, AgentListResult]("agents.list", Query, "root-association", false),
	action[IDParams, AgentTranscriptResult]("agent.transcript", Query, "human-transcript-inspection", false),
	action[AgentInputParams, AgentSubmitResult]("agent.submit", Command, "agent-admission", false),
	action[AgentCancelParams, Empty]("agent.turn.cancel", Command, "target-turn", false),
	action[QuestionAnswerParams, Empty]("question.answer", Command, "pending-question", false),
	action[EmptyParams, ProviderCatalogsResult]("provider.catalogs", Query, "host-runtime", false),
	action[IDParams, Empty]("agent.control", Command, "agent-authority", false),
	action[IDParams, Empty]("agent.delete", Command, "agent-authority", false),
	action[BudgetCapParams, session.BudgetState]("budget.cap", Command, "budget-authority", false),
	action[IDParams, session.CapabilityRecord]("capability.revoke", Command, "capability-authority", false),
	action[ShellParams, TextResult]("shell.run", Command, "tool-permissions", false),
	action[EmptyParams, ContextAuditResult]("context.audit", Query, "root-association", false),
	action[EmptyParams, MCPListResult]("mcp.status", Query, "root-association", false),
	action[MCPServerParams, Empty]("mcp.reconnect", Command, "delegated-mcp-authority", false),
	action[MCPServerParams, Empty]("mcp.enable", Command, "delegated-mcp-authority", false),
	action[MCPServerParams, Empty]("mcp.disable", Command, "delegated-mcp-authority", false),
	action[EmptyParams, MCPImportStatusResult]("mcp.import.status", Query, "host-configuration", false),
	action[MCPImportParams, MCPImportStatusResult]("mcp.import.configure", Command, "host-configuration", false),
	action[EmptyParams, LSPListResult]("lsp.status", Query, "root-association", false),
	action[EmptyParams, BrowserStatusResult]("browser.status", Query, "root-association", false),
	action[BrowserDriverParams, BrowserStatusResult]("browser.set_driver", Command, "host-configuration", false),
	action[EmptyParams, ComputerStatusResult]("computer.status", Query, "root-association", false),
	action[ComputerAppParams, ComputerStatusResult]("computer.allow", Command, "human-computer-policy", false),
	action[ComputerAppParams, ComputerStatusResult]("computer.deny", Command, "human-computer-policy", false),
	action[TerminalInputParams, Empty]("terminal.input", Ephemeral, "active-terminal", true),
	action[ToolConfigureParams, Empty]("tool.configure", Command, "tool-permissions", false),
	action[EmptyParams, ToolSchemaResult]("tool.schema", Query, "tool-authority", false),
	action[ToolCallParams, TextResult]("tool.call", Command, "tool-permissions", false),
	action[PermissionConfigureParams, Empty]("permission.mode", Command, "trusted-client-mode", false),
	action[EmptyParams, PermissionRulesResult]("permission.rules", Query, "root-association", false),
	action[IDParams, Empty]("permission.forget", Command, "rule-authority", false),
	action[MCPAttachParams, Empty]("mcp.attach", Ephemeral, "delegated-mcp-authority", true),
}
