import {createServer} from 'node:http';
import {readFile, mkdir, writeFile} from 'node:fs/promises';
import {resolve, extname, sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
import {chromium, expect} from '@playwright/test';
import {themeCatalog} from '../src/generated/theme-catalog.ts';

const root = fileURLToPath(new URL('../storybook-static/', import.meta.url));
const results = fileURLToPath(new URL('../ui-test-results/', import.meta.url));
await mkdir(results, {recursive: true});
const mime = {'.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json', '.woff2': 'font/woff2', '.svg': 'image/svg+xml'};
const server = createServer(async (req, res) => {
  const path = resolve(root, `.${new URL(req.url, 'http://localhost').pathname === '/' ? '/index.html' : new URL(req.url, 'http://localhost').pathname}`);
  if (!path.startsWith(root.endsWith(sep) ? root : root + sep)) {res.writeHead(403).end(); return;}
  try {res.setHeader('Content-Type', mime[extname(path)] ?? 'application/octet-stream'); res.end(await readFile(path));} catch {res.writeHead(404).end();}
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch();
const page = await browser.newPage({viewport: {width: 1080, height: 960}});
const errors = [];
page.on('pageerror', error => errors.push(error.message));
const story = (id, theme = 'light') => `${origin}/iframe.html?id=whip-library--${id}&viewMode=story&theme=${encodeURIComponent(theme)}&whip_a11y=manual`;
const report = {themes: [], checks: []};
try {
  for (const theme of themeCatalog) {
    await page.goto(story('appearance', theme.id));
    await page.getByRole('heading', {name: 'A quiet space for complex work.'}).waitFor();
    const actual = await page.evaluate(() => ({id: document.documentElement.dataset.theme, color: getComputedStyle(document.documentElement).color, background: getComputedStyle(document.documentElement).backgroundColor, buttonSize: getComputedStyle(document.querySelector('#storybook-root button')).fontSize}));
    if (actual.id !== theme.id) throw new Error(`Theme mismatch ${theme.id}: ${actual.id}`);
    await page.addScriptTag({path: require.resolve('axe-core/axe.min.js')});
    const a11y = await page.evaluate(async () => (await axe.run(document.getElementById('storybook-root'), {runOnly: {type: 'rule', values: ['color-contrast', 'label', 'button-name', 'aria-valid-attr-value']}})).violations.map(item => ({id:item.id, impact:item.impact, nodes:item.nodes.map(node => ({html:node.html, summary:node.failureSummary}))})));
    report.themes.push({id: theme.id, ...actual, violations:a11y});
    if (['light','dark','catppuccin','catppuccin-light'].includes(theme.id)) await page.screenshot({path: resolve(results, `${theme.id}.png`), fullPage: true});
  }
  await page.goto(`${origin}/iframe.html?id=whip-appearance--display-preferences&viewMode=story&theme=dark&whip_a11y=manual`);
  const density = page.getByRole('slider', {name: 'Tool call density'});
  await expect(density).toHaveAttribute('aria-valuetext', 'Compact');
  await density.focus(); await density.press('ArrowRight');
  await expect(density).toHaveAttribute('aria-valuetext', 'Comfortable');
  await density.press('End'); await expect(density).toHaveAttribute('aria-valuetext', 'Detailed');
  await density.press('Home'); await expect(density).toHaveAttribute('aria-valuetext', 'Compact');
  await page.getByRole('button', {name: 'Increase UI font size', exact: true}).click();
  await expect(page.getByRole('button', {name: 'Reset appearance'})).toHaveCSS('font-size', '14px');
  await page.getByRole('button', {name: 'Increase Code font size', exact: true}).click();
  const appearanceCode = page.getByRole('region', {name: 'Appearance code'});
  await expect(appearanceCode).toHaveCSS('font-size', '13px');
  const beforeWrap = await appearanceCode.textContent();
  await page.getByRole('switch', {name: 'Wrap code'}).click();
  await expect(appearanceCode).toHaveCSS('white-space', 'pre-wrap');
  await expect(appearanceCode).toHaveText(beforeWrap);
  await page.getByRole('button', {name: 'Use accessible system presentation'}).click();
  await expect(page.locator('html')).toHaveAttribute('data-contrast', 'more');
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'reduce');
  await page.getByRole('button', {name: 'Open appearance portal'}).click();
  await expect(page.getByRole('button', {name: 'Inherited type'})).toHaveCSS('font-size', '14px');
  if ((await page.getByRole('button', {name: 'Inherited type'}).evaluate(el => getComputedStyle(el).fontFamily)).includes('Inter')) throw new Error('System font did not reach portal');
  await page.keyboard.press('Escape');
  await page.reload();
  await expect(appearanceCode).toHaveCSS('font-size', '13px');
  await expect(appearanceCode).toHaveCSS('white-space', 'pre-wrap');
  await expect(page.locator('html')).toHaveAttribute('data-contrast', 'more');
  await page.getByRole('button', {name: 'Reset appearance'}).click();
  await expect(appearanceCode).toHaveCSS('font-size', '12px');
  await expect(appearanceCode).toHaveCSS('white-space', 'pre');
  await expect(page.getByRole('button', {name: 'Reset appearance'})).toHaveCSS('font-size', '13px');
  const fontInput = page.getByRole('textbox', {name: 'UI font size', exact: true});
  await fontInput.fill('13.5'); await fontInput.press('Tab');
  await expect(fontInput).toHaveValue('14');
  await expect(page.getByRole('button', {name: 'Reset appearance'})).toHaveCSS('font-size', '14px');
  await fontInput.fill('999'); await fontInput.press('Tab');
  await expect(fontInput).toHaveValue('20');
  await fontInput.fill('1'); await fontInput.press('Tab');
  await expect(fontInput).toHaveValue('12');
  await page.getByRole('button', {name: 'Reset appearance'}).click();
  const selectedBeforePreview = await page.locator('html').getAttribute('data-theme');
  const picker = page.getByRole('combobox', {name: /^Color theme:/});
  await picker.click();
  await page.getByRole('combobox', {name: 'Search themes'}).fill('nord');
  await page.getByRole('combobox', {name: 'Search themes'}).press('ArrowDown');
  await expect(page.locator('html')).not.toHaveAttribute('data-theme', selectedBeforePreview);
  await page.keyboard.press('Escape');
  await expect(page.locator('html')).toHaveAttribute('data-theme', selectedBeforePreview);
  await page.keyboard.press('Escape');
  await expect(picker).toBeFocused();
  report.checks.push('appearance slider keyboard/named values, independent fonts, wrapping, portal inheritance, reload, reset and compact theme preview cancellation');
  await page.goto(story('overlay-states', 'dark'));
  // The story's play function exercises first open + escape. Wait for it to finish.
  await page.waitForFunction(() => document.getElementById('storybook-root')?.dataset.playComplete === 'true');
  await page.getByRole('button', {name: 'Open dialog', exact: true}).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button', {name: 'Open nested confirmation'}).click();
  await page.getByRole('alertdialog').waitFor();
  await page.getByRole('button', {name: 'Cancel', exact: true}).click();
  await page.getByRole('alertdialog').waitFor({state: 'hidden'});
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({state: 'hidden'});
  report.checks.push('nested dialogs and focus dismissal');
  const commandTrigger = page.getByRole('button', {name: 'Find command', exact: true});
  const commandSearch = page.getByRole('combobox', {name: 'Search commands'});
  const commandDialog = page.getByRole('dialog', {name: 'Commands', exact: true});
  await commandTrigger.focus();
  await commandTrigger.press('Enter');
  await expect(commandSearch).toBeFocused();
  await page.keyboard.type('Thorough');
  await expect(page.getByRole('option', {name: 'Thorough', exact: true})).toBeVisible();
  await page.keyboard.press('Enter');
  await expect(commandDialog).toBeHidden();
  await expect(commandTrigger).toBeFocused();
  await commandTrigger.press('Enter');
  await expect(commandSearch).toBeFocused();
  await page.keyboard.type('Fast');
  await expect(page.getByRole('option', {name: 'Fast', exact: true})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('listbox')).toBeHidden();
  await expect(commandDialog).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(commandDialog).toBeHidden();
  await expect(commandTrigger).toBeFocused();
  report.checks.push('command picker initial keyboard focus, immediate typing, selection, Escape and focus return');
  await page.goto(story('form-states'));
  const choices = page.getByRole('radiogroup', {name: 'Execution mode'}).getByRole('radio');
  await choices.first().click();
  await choices.first().press('ArrowDown');
  await page.waitForFunction(() => document.querySelectorAll('[role="radiogroup"][aria-label="Execution mode"] [role="radio"]')[1]?.getAttribute('aria-checked') === 'true');
  if (await choices.first().getAttribute('aria-checked') !== 'false' || await choices.nth(1).getAttribute('aria-checked') !== 'true') throw new Error('Radio keyboard navigation did not choose the next answer');
  await page.getByRole('combobox', {name: 'Find a model'}).fill('Thorough');
  await page.getByRole('option', {name: 'Thorough', exact: true}).click();
  if (await page.getByRole('combobox', {name: 'Find a model'}).inputValue() !== 'Thorough') throw new Error('Combobox did not select result');
  report.checks.push('keyboard accessible combobox');
  await page.getByLabel('Session title', {exact: true}).fill('Changed title');
  report.checks.push('Field label association');
  await page.goto(story('native-semantics'));
  for (const [label, width, maxWidth] of [['Dynamic input', '195px', '210px'], ['Dynamic textarea', '205px', '220px']]) {
    const control = page.getByLabel(label, {exact: true});
    const actual = await control.evaluate(el => ({width: getComputedStyle(el).width, maxWidth: getComputedStyle(el).maxWidth}));
    if (actual.width !== width || actual.maxWidth !== maxWidth) throw new Error(`${label} lost dynamic xstyle or native style: ${JSON.stringify(actual)}`);
  }
  for (const role of ['checkbox', 'switch']) {
    const control = page.getByRole(role);
    await control.waitFor();
    const description = await control.getAttribute('aria-describedby');
    if (!description?.split(' ').includes('external-description') || description.split(' ').length !== 2) throw new Error(`${role} discarded the caller or library description`);
    const ownDescription = description.split(' ').find(id => id !== 'external-description');
    const descriptionDisplay = await page.evaluate(id => getComputedStyle(document.getElementById(id)).display, ownDescription);
    if (descriptionDisplay !== 'block') throw new Error(`${role} visually concatenated its label and description`);
  }
  await page.getByRole('button', {name: 'Copy', exact: true}).click();
  await page.getByRole('button', {name: 'Could not copy. Try again.'}).waitFor();
  await page.getByRole('status').filter({hasText: 'Clipboard access is unavailable.'}).waitFor();
  report.checks.push('dynamic xstyle, native descriptions and synchronous clipboard failure');
  await page.goto(story('custom-theme').replace('&theme=light', ''));
  await page.getByRole('button', {name: 'Import resolved custom theme'}).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'test-host:local:ink');
  await page.getByLabel('Draft', {exact: true}).fill('An application-owned draft');
  await page.getByRole('button', {name: 'Imported ink', exact: true}).click();
  const themeDialog = page.getByRole('dialog');
  await themeDialog.getByRole('combobox', {name: 'Search themes'}).fill('nord');
  await themeDialog.getByRole('combobox', {name: 'Search themes'}).press('ArrowDown');
  await page.waitForFunction(() => document.documentElement.dataset.theme !== 'test-host:local:ink');
  await page.keyboard.press('Escape'); // dismiss combobox
  await themeDialog.getByRole('button', {name: 'Close', exact: true}).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'test-host:local:ink');
  if (await page.getByLabel('Draft', {exact: true}).inputValue() !== 'An application-owned draft') throw new Error('Theme preview lost the draft');
  await page.reload();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'test-host:local:ink');
  report.checks.push('custom theme immediate selection, persistence and reversible preview without remounting draft');
  await page.goto(`${origin}/iframe.html?id=whip-appearance--display-preferences&viewMode=story&whip_a11y=manual`);
  await page.getByRole('button', {name: 'Reset appearance', exact: true}).click();
  await page.reload();
  await page.getByRole('combobox', {name: /^Color theme:/}).click();
  await page.getByRole('combobox', {name: 'Search themes'}).fill('Imported ink');
  await page.getByRole('option', {name: /Imported ink/}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'test-host:local:ink');
  await expect(page.getByRole('combobox', {name: 'Color theme: Imported ink'})).toBeFocused();
  await page.goto(story('custom-theme').replace('&theme=light', ''));
  report.checks.push('reset retains imported theme definitions across reload and compact picker selection');
  await page.evaluate(() => localStorage.setItem('whip.appearance.theme.v1', '{broken'));
  await page.reload();
  await page.getByRole('button', {name: 'System appearance', exact: true}).click();
  await page.getByText('Saved theme could not be read. Following your system appearance.').waitFor();
  await page.getByRole('dialog').getByRole('button', {name: 'Close', exact: true}).click();
  await page.emulateMedia({colorScheme: 'dark'});
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
  await page.emulateMedia({colorScheme: 'light'});
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');
  await page.addInitScript(() => {Storage.prototype.setItem = () => {throw new DOMException('Storage unavailable', 'SecurityError');};});
  await page.reload();
  await page.getByRole('button', {name: 'Import resolved custom theme'}).click();
  await page.getByRole('button', {name: 'Imported ink', exact: true}).click();
  await page.getByText('Theme changed for this window, but could not be saved. Check device storage and choose it again to retry.').waitFor();
  report.checks.push('malformed storage fallback, live system appearance and storage-failure selection');
  await page.goto(`${origin}/iframe.html?id=whip-appearance--display-preferences&viewMode=story&whip_a11y=manual`);
  await page.getByRole('button', {name: 'Increase UI font size', exact: true}).click();
  await expect(page.getByRole('button', {name: 'Reset appearance'})).toHaveCSS('font-size', '14px');
  await page.getByRole('status').filter({hasText: 'Display changed for this window, but could not be saved.'}).waitFor();
  report.checks.push('display storage failures remain visible while current-window preferences apply');
  const mobile = await browser.newPage({viewport: {width: 390, height: 844}, isMobile: true, hasTouch: true});
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(story('appearance', 'dark'));
  await mobile.getByRole('heading', {name: 'A quiet space for complex work.'}).waitFor();
  await mobile.screenshot({path: resolve(results, 'phone-dark.png'), fullPage: true});
  const phone = await mobile.getByRole('button', {name: 'dark', exact: true}).evaluate(el => ({overflow: document.documentElement.scrollWidth > innerWidth, target: getComputedStyle(el).minHeight, coarse: matchMedia('(pointer: coarse)').matches, className: el.className}));
  if (phone.overflow || parseInt(phone.target) < 44) throw new Error(`Phone fixture overflows or uses a small touch target: ${JSON.stringify(phone)}`);
  report.checks.push('phone layout and 44px touch controls');
  await mobile.goto(story('overlay-states'));
  await mobile.waitForFunction(() => document.getElementById('storybook-root')?.dataset.playComplete === 'true');
  await mobile.getByRole('button', {name: 'Find command', exact: true}).tap();
  await expect(mobile.getByRole('dialog', {name: 'Commands', exact: true})).toBeVisible();
  await expect(mobile.getByRole('combobox', {name: 'Search commands'})).toBeFocused();
  await mobile.keyboard.type('Thorough');
  await expect(mobile.getByRole('option', {name: 'Thorough', exact: true})).toBeVisible();
  report.checks.push('touch command picker focuses search for immediate typing');
  await mobile.close();
  const catalog = await browser.newPage();
  catalog.on('pageerror', error => errors.push(error.message));
  await catalog.goto(`${origin}/?path=/story/whip-library--form-states`);
  await catalog.getByRole('tab', {name: /^Accessibility/}).click();
  await catalog.getByRole('tab', {name: /^Passes/}).waitFor();
  report.checks.push('normal Storybook Accessibility panel receives automatic scan results');
  await catalog.close();
  if (errors.length) throw new Error(`Browser errors: ${errors.join('\n')}`);
  await writeFile(resolve(results, 'report.json'), JSON.stringify(report, null, 2));
  const failures = report.themes.filter(theme => theme.violations.length);
  if (failures.length) throw new Error(`Accessibility violations in ${failures.map(theme => theme.id).join(', ')}. See report.json.`);
  console.log(`Validated ${report.themes.length} themes and ${report.checks.length} interaction scenarios. Artifacts: ${results}`);
} catch (error) {console.error('Browser errors:', errors); console.error((await page.locator('body').innerText()).slice(0, 4000)); await page.screenshot({path: resolve(results, 'failure.png'), fullPage: true}); throw error;} finally {await browser.close(); await new Promise(resolve => server.close(resolve));}
