import * as stylex from '@stylexjs/stylex';
import type { Meta, StoryObj } from '@storybook/react-vite';
import { useState } from 'react';
import { MoreHorizontal, Plus, Activity } from 'lucide-react';
import { expect, userEvent, within, waitFor } from 'storybook/test';
import { Accordion, CodeBlock, Alert, AlertDialog, Avatar, Badge, Breadcrumbs, Button, ButtonGroup, Checkbox, Collapsible, Combobox, CommandPicker, ContextMenu, CopyButton, Dialog, EmptyState, ErrorState, Field, Fieldset, IconButton, Input, Kbd, Label, Link, Menu, Meter, NumberField, Panel, Popover, Progress, RadioGroup, Row, ScrollArea, Select, Separator, SettingsRow, Sheet, Skeleton, Spinner, Stack, StatusIndicator, Switch, Tabs, Textarea, ThemePicker, ThemePreview, ToggleGroup, Tooltip, useToast, useTheme, themeCatalog, VisuallyHidden } from '../src';

const storyStyles = stylex.create({narrow: {maxWidth: 390}, width: (value: number) => ({width: value})});
const options = [{value: 'balanced', label: 'Balanced', description: 'Steady progress within a bounded budget'}, {value: 'fast', label: 'Fast'}, {value: 'thorough', label: 'Thorough'}, {value: 'unavailable', label: 'Unavailable on this host', disabled: true}];
function Actions() {
  const toast = useToast();
  return <Stack><Row><Button variant="primary">Send message</Button><Button>Stop turn</Button><Button variant="ghost">Inspect</Button><Button variant="danger">Delete session</Button></Row><Row><Button size="sm">Small</Button><Button>Medium</Button><Button size="lg">Large</Button><Button loading>Saving</Button><Button disabled>Unavailable</Button><IconButton label="New session"><Plus size={16}/></IconButton><CopyButton text="A synthetic example"/></Row><ButtonGroup aria-label="Session actions"><Button>Open</Button><Button>Fork</Button></ButtonGroup><ToggleGroup value={['root']} onValueChange={() => {}} items={[{value: 'root', label: 'Root'}, {value: 'children', label: 'Children'}]} label="Show agents"/><Row><Link href="#controls">View controls</Link><Tooltip label="Open command menu"><Kbd>⌘ K</Kbd></Tooltip><Button onClick={() => toast.add({title: 'Preference saved', description: 'This choice stays on this device.'})}>Show notification</Button></Row></Stack>;
}
function Controls() {
  const [value, setValue] = useState('balanced'); const [checked, setChecked] = useState(true);
  return <Stack><Field label="Session title" description="Visible to every connected client."><Input defaultValue="Explore recursive execution"/></Field><Field label="Configuration revision" error="Another client updated these settings. Refresh and try again."><Input defaultValue="12"/></Field><Field label="Message"><Textarea placeholder="Give your agent a clear next step…"/></Field><Fieldset legend="Agent preferences" description="These choices apply to this run."><Checkbox checked={checked} onCheckedChange={setChecked} label="Include reasoning"/><Switch checked={checked} onCheckedChange={setChecked} label="Desktop notifications"/><RadioGroup value={value} onValueChange={setValue} options={options.slice(0, 2)} label="Execution mode"/></Fieldset><Field label="Model effort"><Select label="Model effort" value={value} onValueChange={setValue} options={options}/></Field><Field label="Find a model"><Combobox label="Find a model" value={value} onValueChange={setValue} options={options}/></Field><NumberField label="Budget" value={20} min={1} max={100}/><Label htmlFor="standalone">Standalone label</Label><Input id="standalone" disabled value="Unavailable" readOnly/></Stack>;
}
function Overlays() {
  const [dialog, setDialog] = useState(false); const [sheet, setSheet] = useState(false); const [alert, setAlert] = useState(false); const [commands, setCommands] = useState(false);
  const items = [{id: 'rename', label: 'Rename session', onSelect: () => setDialog(true)}, {id: 'delete', label: 'Delete session', danger: true, onSelect: () => setAlert(true)}];
  return <Stack><Row><Button onClick={() => setDialog(true)}>Open dialog</Button><Button onClick={() => setSheet(true)}>Open sheet</Button><Button onClick={() => setCommands(true)}>Find command</Button><Menu trigger={<IconButton label="Session menu"><MoreHorizontal size={16}/></IconButton>} items={items}/><Popover title="Agent status" trigger={<Button>Popover</Button>}><p>The child agent is waiting for input.</p></Popover></Row><ContextMenu items={items}><Panel>Right-click this session summary.</Panel></ContextMenu><Dialog open={dialog} onOpenChange={setDialog} title="Session settings" description="Updates are shared with other clients." footer={<Button onClick={() => setDialog(false)}>Save changes</Button>}><Field label="Name"><Input defaultValue="Inspect queue lifecycle"/></Field><Menu trigger={<Button>More actions</Button>} items={items}/><Button onClick={() => setAlert(true)}>Open nested confirmation</Button><ThemePicker/></Dialog><Sheet open={sheet} onOpenChange={setSheet} title="Agent details"><p>Read-only activity and context live here.</p></Sheet><AlertDialog open={alert} onOpenChange={setAlert} title="Delete this session?" description="This removes its conversation history." confirmLabel="Delete session" danger onConfirm={() => setAlert(false)}/><CommandPicker open={commands} onOpenChange={setCommands} items={options} onSelect={() => {}}/></Stack>;
}
function Content() {
  const [tab, setTab] = useState('conversation');
  return <Stack><Breadcrumbs><Link href="#">Session</Link><span aria-hidden>/</span><span>Explore</span></Breadcrumbs><Row><Avatar name="Explore agent"/><StatusIndicator tone="success">Completed</StatusIndicator><Badge tone="warning">Waiting for input</Badge><Badge tone="error">Interrupted</Badge><Badge tone="info">Reconnecting</Badge><Spinner/><VisuallyHidden>Loading the latest state</VisuallyHidden></Row><Progress label="Context use" value={42}/><Meter label="Budget consumed" value={18} max={100}/><Tabs value={tab} onValueChange={setTab} items={[{value: 'conversation', label: 'Conversation', content: <p>Your agent has finished the focused check.</p>}, {value: 'activity', label: 'Activity', content: <p>Three child agents are still working.</p>}]}/><Collapsible title="Read tool output"><pre>Stable, bounded tool output.</pre></Collapsible><Accordion items={[{id: 'reasoning', title: 'Reasoning', content: 'Inspect assumptions before making changes.'}]}/><Alert title="Reconnecting" tone="info">Your accepted work continues on the host.</Alert><Skeleton/><SettingsRow label="Show reasoning" description="Keep longer explanations collapsed."><Switch aria-label="Show reasoning"/></SettingsRow><Separator/><ScrollArea aria-label="Long output"><p>Scroll regions retain native keyboard and touch behavior.</p></ScrollArea><EmptyState title="Your work stays on the host" description="Choose a conversation or begin a new one." icon={<Activity size={24}/>} action={<Button>New session</Button>}/><ErrorState error={new Error('The host is temporarily unavailable.')} action={<Button>Try again</Button>}/></Stack>;
}
const meta = {title: 'WHIP/Library', parameters: {layout: 'padded'}} satisfies Meta;
export default meta;
type Story = StoryObj<typeof meta>;
export const ActionStates: Story = {render: () => <Actions/>};
export const FormStates: Story = {render: () => <Controls/>};
export const OverlayStates: Story = {render: () => <Overlays/>, play: async ({canvasElement}) => {const canvas = within(canvasElement); await userEvent.click(canvas.getByRole('button', {name: 'Open dialog'})); const body = within(canvasElement.ownerDocument.body); await expect(body.getByRole('dialog')).toBeVisible(); await waitFor(() => expect(body.getByRole('dialog').contains(canvasElement.ownerDocument.activeElement)).toBe(true)); await userEvent.keyboard('{Escape}'); await waitFor(() => expect(canvas.getByRole('button', {name: 'Open dialog'})).toHaveFocus()); canvasElement.dataset.playComplete = 'true';}};
export const ContentStates: Story = {render: () => <Content/>};
export const Appearance: Story = {render: () => <Stack><ThemePicker/><ThemePreview/><Actions/><Controls/></Stack>};
export const NarrowLayout: Story = {render: () => <div {...stylex.props(storyStyles.narrow)}><Stack><Actions/><Controls/><Content/></Stack></div>};

function CustomThemeRuntime() {
  const {addTheme, setTheme, resolvedTheme} = useTheme();
  return <Stack><Button onClick={() => {const source = themeCatalog.find(theme => theme.id === 'dark')!; addTheme({...source, id: 'test-host:local:ink', name: 'Imported ink', colors: {...source.colors, background: '#10151d'}, code: {...source.code, background: '#111111'}}); setTheme('test-host:local:ink');}}>Import resolved custom theme</Button><span role="status">{resolvedTheme.id}</span><ThemePicker/><ThemePreview/><Field label="Draft"><Textarea defaultValue="Keep this draft while appearance changes."/></Field></Stack>;
}
export const CustomTheme: Story = {render: () => <CustomThemeRuntime/>};

function CodeSamples() {
  const {theme, setTheme} = useTheme();
  return <Stack><Button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>Switch code theme</Button><CodeBlock language="starlark" label="Starlark example" code={'def inspect(name):\n    # Read-only inspection\n    return agents.get(name="explore", limit=12)\n'}/><CodeBlock language="javascript" label="Escaped JavaScript" code={'const value = "<img src=x onerror=alert(1)>";'}/><CodeBlock language="go" code={'package main\nfunc main() { println("hello") }'}/><CodeBlock language="json" code={'{"root_id":"root","budget":12}'}/><CodeBlock language="shell" code={'printf "%s\\n" "$WHIP_HOME"'}/><CodeBlock code={'Unformatted output remains exact.'}/><CodeBlock language="unknown" code="An unsupported language stays plain text."/><CodeBlock language="python" code={'# Large bounded output\n'.repeat(2000)} downloadAction={<Button size="sm">Read full output</Button>}/></Stack>;
}
export const Code: Story = {render: () => <CodeSamples/>};

function NativeSemanticsFixture() {
  const [error, setError] = useState('');
  return <Stack><Field label="Dynamic input"><Input xstyle={storyStyles.width(195)} style={{maxWidth: 210}}/></Field><Field label="Dynamic textarea"><Textarea xstyle={storyStyles.width(205)} style={{maxWidth: 220}}/></Field><p id="external-description">An application-supplied description.</p><Checkbox label="Preserved checkbox" description="The library description." aria-describedby="external-description"/><Switch label="Preserved switch" description="The library description." aria-describedby="external-description"/><CopyButton text="Unavailable clipboard fixture" copy={() => {throw new Error('Clipboard access is unavailable.');}} onError={value => setError(String(value))}/>{error && <p role="status">{error}</p>}</Stack>;
}
export const NativeSemantics: Story = {render: () => <NativeSemanticsFixture/>};
